### PR TITLE
secure-tokens: fix formatting

### PR DESCRIPTION
**Pull request by keithamus**
Fixes wonky formatting here

### CODE REVIEW

**Comment by keithamus** [comment]
Is someone from @chaijs/core able to review?

**Comment by astorije** [comment]
@keithamus, I think there are stilll some issues with this, such as:

screen shot 2017-09-13 at 18 49 52

Or is that expected like this?

**Comment by astorije** [comment]
Also, mind fixing conflicts?

**Comment by keithamus** [comment]
That's expected. The "pro tip" line is from Travis, the recommendation is _not_ to do that.

I'll fix conflicts when I next can

**Comment by astorije** [comment]
Noted! Will review after you fix conflicts, feel free to ping me when you're done.

**Review by vieiralucas — APPROVED** [review]
I'm not very familiar with this but the formatting fixes LGTM

**Comment by keithamus** [comment]
I think I've confused myself... I must have fixed this before, by the looks of https://github.com/chaijs/guidelines/commit/df90cd0af399d2264036cac3d144072c8929a5c1

**Comment by vieiralucas** [comment]
😸

**Pull request closed without merging**
